### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by combatneko** [PassTheWessel/wumpfetch#14]
Please add benchmarks. Otherwise the “fast” part of the repo description is meaningless.

**Comment by PassTheWessel** [comment]
Thanks for your request, I'll add this to the readme soon!

**Comment by PassTheWessel** [comment]
I've added it in commit [`6ca310c`](https://github.com/PassTheWessel/wumpfetch/commit/6ca310c0c84c29dbb638f0ae3e7f118d65948d65), this was the first time i did a benchmark so please tell me if I did somenthing wrong :)

**Comment by combatneko** [comment]
Geez, these node http libs are slow.

**Comment by PassTheWessel** [comment]
> 
> 
> Geez, these node http libs are slow.

My internet also isn't the best, I'll re-do the benchmark when I get back with my ethernet

**Comment by combatneko** [comment]
It’s best if you do benchmarks from servers with little to no load.

**Comment by PassTheWessel** [comment]
Ah okay, I'll go and do that then :D

**Comment by ohlookitsderpy** [comment]
new benchmarks coming soon, can confirm wumpfetch is fastest
